#!/bin/sh
# R for HarmonyOS 安装后处理脚本
# 在 make install 之后运行，一键解决所有安装后问题。
#
# 用法: cd /path/to/R-harmonyos && bash post-install-R.sh
#
# 执行内容:
#   1. 生成 methods 包懒加载数据库（必需，否则 stats4 等包无法加载）
#   2. 生成 NEWS.rds / NEWS.2.rds / NEWS.3.rds（缺少时 make install 会失败）
#   3. 验证安装完整性

set -e

# Version selection:  bash post-install-R.sh [version]
# Default is R 4.4.3.
R_VERSION="${1:-4.4.3}"

# ------ 配置 ------
# R_HOME 自动检测（优先已安装路径，其次 build 路径）
if [ -x "$HOME/.local/R/lib/R/bin/R" ]; then
    R_BIN="$HOME/.local/R/lib/R/bin/R"
    R_HOME="$HOME/.local/R/lib/R"
elif [ -x "build/bin/R" ]; then
    R_BIN="$(pwd)/build/bin/R"
    R_HOME="$(pwd)/build"
else
    echo "Error: 找不到 R 可执行文件。请先运行 make install 或确认编译已完成。"
    echo "  查找位置: $HOME/.local/R/lib/R/bin/R"
    echo "           build/bin/R"
    exit 1
fi

BUILD_DIR="$(pwd)/build"
R_SRC="$(pwd)/src/R-${R_VERSION}"

echo "=== R for HarmonyOS 安装后处理 ==="
echo "R 可执行文件: $R_BIN"
echo "R_HOME:       $R_HOME"
echo "构建目录:     $BUILD_DIR"
echo ""

# ------ 1. 编译并安装 libohos_stubs.so ------
echo "--- [1/3] 编译 libohos_stubs.so ---"
OHOS_STUBS_SRC="${R_SRC}/src/extra/ohos_stubs/ohos_stubs.c"
OHOS_STUBS_DEST="$R_HOME/lib/libohos_stubs.so"
if [ -f "$OHOS_STUBS_DEST" ]; then
    echo "  [跳过] $OHOS_STUBS_DEST 已存在"
elif [ ! -f "$OHOS_STUBS_SRC" ]; then
    echo "  [跳过] $OHOS_STUBS_SRC 不存在"
    echo "  （先运行 configure-R.sh 或 apply-patches.sh 以复制新文件）"
else
    OHOS_CLANG="/data/service/hnp/bin/aarch64-unknown-linux-ohos-clang"
    if [ ! -x "$OHOS_CLANG" ]; then
        echo "  [错误] 找不到 OHOS clang: $OHOS_CLANG"
        echo "  （请先安装 OHOS SDK）"
    else
        echo "  编译 libohos_stubs.so ..."
        BUILD_TMP=$(mktemp -p "${TMPDIR:-/storage/Users/currentUser/R-harmonyos/tmp}" -d ohos_stubs_build_XXXXXX)
        "$OHOS_CLANG" -c -fPIC "$OHOS_STUBS_SRC" -o "$BUILD_TMP/ohos_stubs.o"
        "$OHOS_CLANG" -shared -o "$BUILD_TMP/libohos_stubs.so" "$BUILD_TMP/ohos_stubs.o"
        cp "$BUILD_TMP/libohos_stubs.so" "$OHOS_STUBS_DEST"
        rm -rf "$BUILD_TMP"
        echo "  [完成] libohos_stubs.so 已安装到 $OHOS_STUBS_DEST"
    fi
fi
echo ""

# ------ 2. 生成 methods 包懒加载数据库 ------
echo "--- [2/3] 生成 methods 包懒加载数据库 ---"
METHODS_DIR="$R_HOME/library/methods/R"
if [ -f "$METHODS_DIR/methods.rdb" ] && [ -f "$METHODS_DIR/methods.rdx" ]; then
    echo "  [跳过] methods 懒加载数据库已存在:"
    echo "    $METHODS_DIR/methods.rdb"
    echo "    $METHODS_DIR/methods.rdx"
else
    echo 'tools:::makeLazyLoading("methods", compress = FALSE)' | \
        R_DEFAULT_PACKAGES=NULL LC_ALL=C "$R_BIN" --vanilla --no-echo
    echo "  [完成] methods 懒加载数据库已生成"
fi
echo ""

# ------ 3. 生成 NEWS.rds ------
echo "--- [3/3] 生成 NEWS.rds ---"
if [ ! -d "$BUILD_DIR/doc" ]; then
    echo "  [跳过] $BUILD_DIR/doc 不存在，跳过 NEWS.rds 生成"
    echo "  （make install 可能需要手动处理）"
else
    cd "$BUILD_DIR/doc"

    for news_rd in NEWS.Rd NEWS.2.Rd NEWS.3.Rd; do
        news_rds="${news_rd%.Rd}.rds"
        if [ -f "$news_rds" ]; then
            echo "  [跳过] $news_rds 已存在"
            continue
        fi
        # 检查源文件是否存在
        src_rd="../../src/R-${R_VERSION}/doc/$news_rd"
        if [ ! -f "$src_rd" ]; then
            echo "  [跳过] $src_rd 不存在"
            continue
        fi
        echo "  生成 $news_rds ..."
        LC_ALL=C "$R_BIN" --vanilla --no-echo -e \
            'options(warn=1); saveRDS(tools:::prepare_Rd(tools::parse_Rd(
              "'"$src_rd"'",
              macros = "../share/Rd/macros/system.Rd"), stages = "install",
              warningCalls = FALSE), "'"$news_rds"'")' 2>/dev/null || \
        echo "  [警告] $news_rds 生成失败（make install 可能会重试）"
    done

    cd "$(pwd)"  # 回到原始目录
    echo "  [完成] NEWS.rds 处理完毕"
fi
echo ""

# ------ 4. 修复已安装 R 的 CC17/CC23 ------
echo "--- [4/6] 修复 CC17/CC23 ---"
for mc in "$R_HOME/etc/Makeconf" "$BUILD_DIR/etc/Makeconf"; do
    if [ -f "$mc" ]; then
        for cv in CC17 CC23; do
            if grep -q "^${cv} = \$" "$mc" 2>/dev/null; then
                sed -i "s|^${cv} = \$|${cv} = ${OHOS_CLANG:-/data/service/hnp/bin/aarch64-unknown-linux-ohos-clang}|" "$mc"
                echo "  [OK] 已修复 $mc 中的 ${cv}"
            fi
        done
    fi
done
echo ""

# ------ 5. 配置用户 R 环境（~/.Rprofile）------
echo "--- [5/6] 配置 ~/.Rprofile ---"
RPROFILE="${HOME}/.Rprofile"
TMPDIR_DEFAULT="/data/storage/el4/base/R-build"
PATCH_RCPP_SCRIPT="$(pwd)/versions/4.6.0/patch-rcpp.sh"

mkdir -p "$TMPDIR_DEFAULT"
mkdir -p "${HOME}/.R"

if [ -f "$RPROFILE" ] && ! grep -q "HarmonyOS" "$RPROFILE" 2>/dev/null; then
    cp "$RPROFILE" "${RPROFILE}.bak.$(date +%Y%m%d_%H%M%S)"
fi

cat > "$RPROFILE" << RPROFILE_EOF
# =============================================================
# HarmonyOS R configuration (auto-generated by post-install-R.sh)
# =============================================================

# ---- TMPDIR ----
TMPDIR <- "${TMPDIR_DEFAULT}"
dir.create(TMPDIR, showWarnings = FALSE, recursive = TRUE)
Sys.setenv(TMPDIR = TMPDIR)

# ---- .libPaths ----
r_lib <- "${R_HOME}/library"
if (r_lib %in% .libPaths()) {
    .libPaths(c(r_lib, .libPaths()[-which(.libPaths() == r_lib)]))
}

# ---- harmony_install() ----
harmony_install <- function(pkgs,
                             repos = "https://mirrors.tuna.tsinghua.edu.cn/CRAN",
                             bioc = FALSE, github = FALSE, ...) {
    # GitHub 包必须用 "owner/repo" 格式，例如 "satijalab/seurat-wrappers"。
    # 不要只用包名（如 "seurat-wrappers"），否则可能匹配到多个仓库。
    if (bioc || github) {
        if (!requireNamespace("remotes", quietly = TRUE)) {
            message("Installing remotes ...")
            install.packages("remotes", repos = repos,
                             configure.args = "--host=aarch64-linux-ohos",
                             INSTALL_opts = "--no-test-load")
        }
    }
    if (bioc && !requireNamespace("BiocManager", quietly = TRUE)) {
        message("Installing BiocManager ...")
        install.packages("BiocManager", repos = repos,
                         configure.args = "--host=aarch64-linux-ohos",
                         INSTALL_opts = "--no-test-load")
    }
    for (pkg in pkgs) {
        message("Installing: ", pkg)
        tryCatch({
            if (bioc) {
                BiocManager::install(pkg,
                    configure.args = "--host=aarch64-linux-ohos",
                    INSTALL_opts = "--no-test-load",
                    ...)
            } else if (github) {
                remotes::install_github(pkg,
                    configure.args = "--host=aarch64-linux-ohos",
                    INSTALL_opts = "--no-test-load",
                    ...)
            } else {
                install.packages(pkg,
                    repos = repos,
                    configure.args = "--host=aarch64-linux-ohos",
                    INSTALL_opts = "--no-test-load",
                    ...)
            }
        }, error = function(e) {
            message("Retrying without configure.args: ", pkg)
            if (bioc) {
                BiocManager::install(pkg,
                    INSTALL_opts = "--no-test-load", ...)
            } else if (github) {
                remotes::install_github(pkg,
                    INSTALL_opts = "--no-test-load", ...)
            } else {
                install.packages(pkg,
                    repos = repos,
                    INSTALL_opts = "--no-test-load", ...)
            }
        })
    }
    # Auto-patch Rcpp undoRmath.h when Rcpp is installed
    if ("Rcpp" %in% rownames(installed.packages())) {
        undo_file <- file.path(.libPaths()[1], "Rcpp", "include",
                               "Rcpp", "sugar", "undoRmath.h")
        if (file.exists(undo_file)) {
            tx <- readLines(undo_file)
            if (!any(grepl("^#undef log1p\$", tx))) {
                idx <- grep("^#undef log1pmx\$", tx)
                if (length(idx) == 1) {
                    tx <- append(tx, "#undef log1p", after = idx[1] - 1)
                    writeLines(tx, undo_file)
                    message("Patched Rcpp undoRmath.h (undef log1p)")
                }
            }
        }
    }
}

if (interactive()) {
    message("R on HarmonyOS | TMPDIR=", Sys.getenv("TMPDIR"))
    message("Use harmony_install() for packages with configure scripts")
}
RPROFILE_EOF

echo "  [OK] $RPROFILE 已创建"

# Also add TMPDIR to shell profile if not already there
SHELL_PROFILE="${HOME}/.bashrc"
if [ -f "$SHELL_PROFILE" ]; then
    if ! grep -q "export TMPDIR=${TMPDIR_DEFAULT}" "$SHELL_PROFILE" 2>/dev/null; then
        echo "" >> "$SHELL_PROFILE"
        echo "# HarmonyOS R build temp directory" >> "$SHELL_PROFILE"
        echo "export TMPDIR=${TMPDIR_DEFAULT}" >> "$SHELL_PROFILE"
        echo "  [OK] TMPDIR 已添加到 $SHELL_PROFILE"
    else
        echo "  [跳过] TMPDIR 已在 $SHELL_PROFILE 中"
    fi
fi
echo ""

# ------ 5. 验证安装完整性 ------
echo "--- [5/5] 验证安装完整性 ---"
ERRORS=0

check_file() {
    local file="$1" desc="$2"
    if [ -f "$file" ]; then
        echo "  [OK] $desc"
    else
        echo "  [ERR] $desc: 缺少 $file"
        ERRORS=$((ERRORS + 1))
    fi
}

check_file "$R_HOME/bin/exec/R" "R 主二进制"
check_file "$R_HOME/lib/libR.so" "libR.so"
check_file "$R_HOME/library/base/R/base" "base 包"
check_file "$R_HOME/library/methods/R/methods" "methods 包 (nspackloader)"
check_file "$R_HOME/library/methods/R/methods.rdb" "methods.rdb"
check_file "$R_HOME/library/methods/R/methods.rdx" "methods.rdx"
check_file "$R_HOME/library/stats/R/stats" "stats 包"
check_file "$R_HOME/library/graphics/R/graphics" "graphics 包"
check_file "$R_HOME/library/grDevices/R/grDevices" "grDevices 包"
check_file "$R_HOME/library/utils/R/utils" "utils 包"
check_file "$R_HOME/lib/libohos_stubs.so" "libohos_stubs.so"

echo ""
if [ $ERRORS -eq 0 ]; then
    echo "=== 安装后处理全部完成，验证通过 ==="
else
    echo "=== 完成（$ERRORS 个文件缺失，请检查上述 [ERR] 项）==="
fi
